name: Run SearchByDoubleFiltering

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-submission:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t team_df .

    - name: Create result directory
      run: mkdir -p result

    - name: Run Docker container
      run: |
        docker run \
          -v ${{ github.workspace }}/benchmark-dev-pubmed23.h5:/app/data/benchmark-dev-pubmed23.h5:ro \
          -v ${{ github.workspace }}/result:/app/result \
          team_df /bin/bash /app/autoexec_all_pubmed23.sh

    - name: Archive result
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: result/
